name: Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run CI tests
        run: sudo ./tests/run_ci_tests.sh

  build_and_publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    # Only run this job on push to main
    if: github.event_name == 'push'
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push :legacy image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            IPTABLES_MODE=legacy
            ALPINE_VERSION=3.15
          push: true
          tags: ghcr.io/${{ github.repository }}:legacy

      - name: Build and push :nft image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            IPTABLES_MODE=nft
            ALPINE_VERSION=3.19
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:nft
            ghcr.io/${{ github.repository }}:latest
